"""add rag audit logs

Revision ID: 21ef85ee483a
Revises: 4adc5d0f0bf2
Create Date: 2026-09-06 22:07:11.060888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21ef85ee483a'
down_revision: Union[str, Sequence[str], None] = '4adc5d0f0bf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_used', sa.String(length=20), nullable=False),
    sa.Column('question_hash', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('source_document_ids', sa.JSON(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("outcome IN ('answered', 'refused', 'error')", name='ck_audit_valid_outcome'),
    sa.CheckConstraint('duration_ms >= 0', name='ck_audit_duration_nonnegative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_audit_logs_created_at'), 'rag_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_rag_audit_logs_request_id'), 'rag_audit_logs', ['request_id'], unique=True)
    op.create_index(op.f('ix_rag_audit_logs_user_id'), 'rag_audit_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rag_audit_logs_user_id'), table_name='rag_audit_logs')
    op.drop_index(op.f('ix_rag_audit_logs_request_id'), table_name='rag_audit_logs')
    op.drop_index(op.f('ix_rag_audit_logs_created_at'), table_name='rag_audit_logs')
    op.drop_table('rag_audit_logs')
    # ### end Alembic commands ###
